[project]
name = "vscode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-experimental>=0.3.4",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
]
